// Code generated by protoc-gen-go. DO NOT EDIT.
// source: other_restaurant.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetOtherRestaurantByIDRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOtherRestaurantByIDRequest) Reset()         { *m = GetOtherRestaurantByIDRequest{} }
func (m *GetOtherRestaurantByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetOtherRestaurantByIDRequest) ProtoMessage()    {}
func (*GetOtherRestaurantByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_other_restaurant_f2a041f5b7c0b82c, []int{0}
}
func (m *GetOtherRestaurantByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtherRestaurantByIDRequest.Unmarshal(m, b)
}
func (m *GetOtherRestaurantByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtherRestaurantByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetOtherRestaurantByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtherRestaurantByIDRequest.Merge(dst, src)
}
func (m *GetOtherRestaurantByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetOtherRestaurantByIDRequest.Size(m)
}
func (m *GetOtherRestaurantByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtherRestaurantByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtherRestaurantByIDRequest proto.InternalMessageInfo

func (m *GetOtherRestaurantByIDRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetOtherRestaurantByIDResponse struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=Restaurant" json:"Restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetOtherRestaurantByIDResponse) Reset()         { *m = GetOtherRestaurantByIDResponse{} }
func (m *GetOtherRestaurantByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetOtherRestaurantByIDResponse) ProtoMessage()    {}
func (*GetOtherRestaurantByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_other_restaurant_f2a041f5b7c0b82c, []int{1}
}
func (m *GetOtherRestaurantByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtherRestaurantByIDResponse.Unmarshal(m, b)
}
func (m *GetOtherRestaurantByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtherRestaurantByIDResponse.Marshal(b, m, deterministic)
}
func (dst *GetOtherRestaurantByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtherRestaurantByIDResponse.Merge(dst, src)
}
func (m *GetOtherRestaurantByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetOtherRestaurantByIDResponse.Size(m)
}
func (m *GetOtherRestaurantByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtherRestaurantByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtherRestaurantByIDResponse proto.InternalMessageInfo

func (m *GetOtherRestaurantByIDResponse) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type Restaurant struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	ClientUid            uint64   `protobuf:"varint,4,opt,name=client_uid,json=clientUid" json:"client_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_other_restaurant_f2a041f5b7c0b82c, []int{2}
}
func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (dst *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(dst, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Restaurant) GetClientUid() uint64 {
	if m != nil {
		return m.ClientUid
	}
	return 0
}

func init() {
	proto.RegisterType((*GetOtherRestaurantByIDRequest)(nil), "proto.GetOtherRestaurantByIDRequest")
	proto.RegisterType((*GetOtherRestaurantByIDResponse)(nil), "proto.GetOtherRestaurantByIDResponse")
	proto.RegisterType((*Restaurant)(nil), "proto.Restaurant")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OtherRestaurantService service

type OtherRestaurantServiceClient interface {
	GetOtherRestaurantByID(ctx context.Context, in *GetOtherRestaurantByIDRequest, opts ...grpc.CallOption) (*GetOtherRestaurantByIDResponse, error)
}

type otherRestaurantServiceClient struct {
	cc *grpc.ClientConn
}

func NewOtherRestaurantServiceClient(cc *grpc.ClientConn) OtherRestaurantServiceClient {
	return &otherRestaurantServiceClient{cc}
}

func (c *otherRestaurantServiceClient) GetOtherRestaurantByID(ctx context.Context, in *GetOtherRestaurantByIDRequest, opts ...grpc.CallOption) (*GetOtherRestaurantByIDResponse, error) {
	out := new(GetOtherRestaurantByIDResponse)
	err := grpc.Invoke(ctx, "/proto.OtherRestaurantService/GetOtherRestaurantByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OtherRestaurantService service

type OtherRestaurantServiceServer interface {
	GetOtherRestaurantByID(context.Context, *GetOtherRestaurantByIDRequest) (*GetOtherRestaurantByIDResponse, error)
}

func RegisterOtherRestaurantServiceServer(s *grpc.Server, srv OtherRestaurantServiceServer) {
	s.RegisterService(&_OtherRestaurantService_serviceDesc, srv)
}

func _OtherRestaurantService_GetOtherRestaurantByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtherRestaurantByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtherRestaurantServiceServer).GetOtherRestaurantByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OtherRestaurantService/GetOtherRestaurantByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtherRestaurantServiceServer).GetOtherRestaurantByID(ctx, req.(*GetOtherRestaurantByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OtherRestaurantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OtherRestaurantService",
	HandlerType: (*OtherRestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOtherRestaurantByID",
			Handler:    _OtherRestaurantService_GetOtherRestaurantByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "other_restaurant.proto",
}

func init() {
	proto.RegisterFile("other_restaurant.proto", fileDescriptor_other_restaurant_f2a041f5b7c0b82c)
}

var fileDescriptor_other_restaurant_f2a041f5b7c0b82c = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x2f, 0xc9, 0x48,
	0x2d, 0x8a, 0x2f, 0x4a, 0x2d, 0x2e, 0x49, 0x2c, 0x2d, 0x4a, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xfa, 0x5c, 0xb2, 0xee, 0xa9, 0x25, 0xfe, 0x20, 0x35,
	0x41, 0x70, 0x25, 0x4e, 0x95, 0x9e, 0x2e, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c,
	0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0xc1,
	0x5c, 0x72, 0xb8, 0x34, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x19, 0x72, 0x71, 0x21, 0x64,
	0xc0, 0x3a, 0xb9, 0x8d, 0x04, 0x21, 0xb6, 0xea, 0x21, 0x24, 0x82, 0x90, 0x14, 0x29, 0x25, 0x23,
	0x6b, 0x41, 0xb7, 0x52, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x06, 0x89, 0x95, 0x24, 0xa6, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x83, 0xc4,
	0x40, 0x6c, 0x21, 0x59, 0x2e, 0xae, 0xe4, 0x9c, 0xcc, 0xd4, 0xbc, 0x92, 0xf8, 0xd2, 0xcc, 0x14,
	0x09, 0x16, 0xb0, 0x7e, 0x4e, 0x88, 0x48, 0x68, 0x66, 0x8a, 0x51, 0x23, 0x23, 0x97, 0x18, 0x9a,
	0xbb, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xd2, 0xb9, 0xc4, 0xb0, 0x7b, 0x4a, 0x48,
	0x05, 0xea, 0x70, 0xbc, 0x81, 0x24, 0xa5, 0x4a, 0x40, 0x15, 0x24, 0x64, 0x94, 0x18, 0x92, 0xd8,
	0xc0, 0xea, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x3d, 0x10, 0xdb, 0x96, 0x01, 0x00,
	0x00,
}
