// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restaurant.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRestaurantByIDRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRestaurantByIDRequest) Reset()         { *m = GetRestaurantByIDRequest{} }
func (m *GetRestaurantByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetRestaurantByIDRequest) ProtoMessage()    {}
func (*GetRestaurantByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_restaurant_63645da9fcd4dfb3, []int{0}
}
func (m *GetRestaurantByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRestaurantByIDRequest.Unmarshal(m, b)
}
func (m *GetRestaurantByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRestaurantByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetRestaurantByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRestaurantByIDRequest.Merge(dst, src)
}
func (m *GetRestaurantByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetRestaurantByIDRequest.Size(m)
}
func (m *GetRestaurantByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRestaurantByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRestaurantByIDRequest proto.InternalMessageInfo

func (m *GetRestaurantByIDRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRestaurantByIDResponse struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=Restaurant" json:"Restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRestaurantByIDResponse) Reset()         { *m = GetRestaurantByIDResponse{} }
func (m *GetRestaurantByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetRestaurantByIDResponse) ProtoMessage()    {}
func (*GetRestaurantByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_restaurant_63645da9fcd4dfb3, []int{1}
}
func (m *GetRestaurantByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRestaurantByIDResponse.Unmarshal(m, b)
}
func (m *GetRestaurantByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRestaurantByIDResponse.Marshal(b, m, deterministic)
}
func (dst *GetRestaurantByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRestaurantByIDResponse.Merge(dst, src)
}
func (m *GetRestaurantByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetRestaurantByIDResponse.Size(m)
}
func (m *GetRestaurantByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRestaurantByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRestaurantByIDResponse proto.InternalMessageInfo

func (m *GetRestaurantByIDResponse) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type Restaurant struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	ClientUid            uint64   `protobuf:"varint,4,opt,name=client_uid,json=clientUid" json:"client_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_restaurant_63645da9fcd4dfb3, []int{2}
}
func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (dst *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(dst, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Restaurant) GetClientUid() uint64 {
	if m != nil {
		return m.ClientUid
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRestaurantByIDRequest)(nil), "proto.GetRestaurantByIDRequest")
	proto.RegisterType((*GetRestaurantByIDResponse)(nil), "proto.GetRestaurantByIDResponse")
	proto.RegisterType((*Restaurant)(nil), "proto.Restaurant")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RestaurantService service

type RestaurantServiceClient interface {
	GetRestaurantByID(ctx context.Context, in *GetRestaurantByIDRequest, opts ...grpc.CallOption) (*GetRestaurantByIDResponse, error)
}

type restaurantServiceClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantServiceClient(cc *grpc.ClientConn) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) GetRestaurantByID(ctx context.Context, in *GetRestaurantByIDRequest, opts ...grpc.CallOption) (*GetRestaurantByIDResponse, error) {
	out := new(GetRestaurantByIDResponse)
	err := grpc.Invoke(ctx, "/proto.RestaurantService/GetRestaurantByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RestaurantService service

type RestaurantServiceServer interface {
	GetRestaurantByID(context.Context, *GetRestaurantByIDRequest) (*GetRestaurantByIDResponse, error)
}

func RegisterRestaurantServiceServer(s *grpc.Server, srv RestaurantServiceServer) {
	s.RegisterService(&_RestaurantService_serviceDesc, srv)
}

func _RestaurantService_GetRestaurantByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RestaurantService/GetRestaurantByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantByID(ctx, req.(*GetRestaurantByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestaurantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantByID",
			Handler:    _RestaurantService_GetRestaurantByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurant.proto",
}

func init() { proto.RegisterFile("restaurant.proto", fileDescriptor_restaurant_63645da9fcd4dfb3) }

var fileDescriptor_restaurant_63645da9fcd4dfb3 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4a, 0x2d, 0x2e,
	0x49, 0x2c, 0x2d, 0x4a, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53,
	0x4a, 0x5a, 0x5c, 0x12, 0xee, 0xa9, 0x25, 0x41, 0x70, 0x59, 0xa7, 0x4a, 0x4f, 0x97, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0x96, 0x20, 0xa6, 0xcc, 0x14, 0x25, 0x3f, 0x2e, 0x49, 0x2c, 0x6a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x0c, 0xb9, 0xb8, 0x10, 0x32, 0x60, 0x4d, 0xdc, 0x46, 0x82, 0x10, 0xbb, 0xf4, 0x10,
	0x12, 0x41, 0x48, 0x8a, 0x94, 0x92, 0x91, 0xb5, 0xa0, 0xdb, 0x26, 0x24, 0xc4, 0xc5, 0x92, 0x97,
	0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x83, 0xc4, 0x4a, 0x12, 0xd3,
	0x8b, 0x25, 0x98, 0x15, 0x98, 0x41, 0x62, 0x20, 0xb6, 0x90, 0x2c, 0x17, 0x57, 0x72, 0x4e, 0x66,
	0x6a, 0x5e, 0x49, 0x7c, 0x69, 0x66, 0x8a, 0x04, 0x0b, 0x58, 0x3f, 0x27, 0x44, 0x24, 0x34, 0x33,
	0xc5, 0x28, 0x97, 0x4b, 0x10, 0x61, 0x49, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x04,
	0x97, 0x20, 0x86, 0x4f, 0x84, 0xe4, 0xa1, 0xae, 0xc5, 0x15, 0x1e, 0x52, 0x0a, 0xb8, 0x15, 0x40,
	0x02, 0x41, 0x89, 0x21, 0x89, 0x0d, 0xac, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x6a,
	0x8d, 0xd8, 0x71, 0x01, 0x00, 0x00,
}
